### ISSUE TITLE
go run main.go and go build main.go errors

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Lallassu/gizmo#4]
misakamikoto@RailGun:~/公共的/gizmo$ go run main.go
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# command-line-arguments
./main.go:19:2: undefined: global
./main.go:22:16: undefined: GameTitle
./main.go:23:38: undefined: global
./main.go:24:16: undefined: global
./main.go:25:16: undefined: global
./main.go:27:5: undefined: global
./main.go:31:2: undefined: Debug
./main.go:39:2: undefined: centerWindow
./main.go:40:2: undefined: global
./main.go:45:2: undefined: printMemoryUsage
./main.go:45:2: too many errors

**Comment by Lallassu** [comment]
You need to init go modules and also get the latest commit of the pixel library. It includes a PR that I added for exporting vPosition from vertex shader to fragment shader. The GL error is appearing on Linux from the gl library but it's not critical.
```
go mod init gizmo
go get github.com/faiface/pixel@e51d4a6676fa48c83b5ea703cb5b044e2967cb83
go run .
```

**Comment by Yakumo-Yukari** [comment]
> You need to init go modules and also get the latest commit of the pixel library. It includes a PR that I added for exporting vPosition from vertex shader to fragment shader. The GL error is appearing on Linux from the gl library but it's not critical.
> 
> ```
> go mod init gizmo
> go get github.com/faiface/pixel@e51d4a6676fa48c83b5ea703cb5b044e2967cb83
> go run .
> ```

`go mod init gizmo
`
go: creating new go.mod: module gizmo

`go get github.com/faiface/pixel@e51d4a6676fa48c83b5ea703cb5b044e2967cb83
`
go: downloading github.com/faiface/pixel v0.8.1-0.20191105235048-e51d4a6676fa
go: github.com/faiface/pixel e51d4a6676fa48c83b5ea703cb5b044e2967cb83 => v0.8.1-0.20191105235048-e51d4a6676fa

`go run .`

> go: finding module for package github.com/faiface/beep
go: finding module for package github.com/faiface/beep/mp3
go: downloading github.com/faiface/glhf v0.0.0-20181018222622-82a6317ac380
go: finding module for package github.com/faiface/beep/wav
go: downloading github.com/faiface/mainthread v0.0.0-20171120011319-8b78f0a41ae3
go: finding module for package github.com/faiface/beep/speaker
go: finding module for package github.com/pkg/profile
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/go-gl/mathgl v0.0.0-20190416160123-c4601bc793c7
go: downloading github.com/go-gl/glfw v0.0.0-20190409004039-e6da0acd62b1
go: downloading github.com/faiface/beep v1.0.2
go: downloading github.com/pkg/profile v1.4.0
go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
go: downloading golang.org/x/image v0.0.0-20190523035834-f03afa92d3ff
go: found github.com/faiface/beep in github.com/faiface/beep v1.0.2
go: found github.com/pkg/profile in github.com/pkg/profile v1.4.0
go: downloading github.com/hajimehoshi/go-mp3 v0.1.1
go: downloading github.com/hajimehoshi/oto v0.3.1
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/hajimehoshi/oto
../../pkg/mod/github.com/hajimehoshi/oto@v0.3.1/driver_linux.go:23:10: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Are there any errors in my steps but still unable to launch gizmo

**Comment by Lallassu** [comment]
It's due to the sound library. But I haven't added any sounds other than the base for using sounds. So do a `git pull` and fetch my latest commit where I have removed sounds and also added `go.mod` pointing out correct version of pixel lib.

**Comment by Yakumo-Yukari** [comment]
> It's due to the sound library. But I haven't added any sounds other than the base for using sounds. So do a `git pull` and fetch my latest commit where I have removed sounds and also added `go.mod` pointing out correct version of pixel lib.

Thanks
