### ISSUE TITLE
unable to start the game

### ISSUE THREAD

**Issue by zillani** [Lallassu/gizmo#5]
Hi, I'm unable to start the game when I select "new game" the screen loads back to the same screen, "the main menu".

**Comment by Lallassu** [comment]
The menu isn't really completed, so you just hit "Esc" and you will be able to play the game :)

**Comment by zillani** [comment]
Awesome man! Love it! Thank you so much. I will learn and contribute to it.

Love from India 🇮🇳

Thanks,
Shaik
